-- Data Definition Language

CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_price     NUMERIC(38, 2),
    discount_price NUMERIC(38, 2),
    title          VARCHAR(255),
    thumbnail_url  VARCHAR(255),
    deleted        BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE categories (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deleted  BOOLEAN NOT NULL,
    name     VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_category_deleted_false ON categories (id) WHERE deleted = false;

CREATE TABLE category_product (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category_id BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_category_product_category_id_product_id ON category_product (category_id, product_id);
CREATE INDEX idx_category_product_product_id ON category_product (product_id);
