-- Data Definition Language

CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_price     NUMERIC(38, 2),
    discount_price NUMERIC(38, 2),
    title          VARCHAR(255),
    thumbnail_url  VARCHAR(255),
    deleted        BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE product_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deleted BOOLEAN NOT NULL,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(38,2) NOT NULL,
    stock INTEGER NOT NULL,
    product_id BIGINT NOT NULL
);

CREATE INDEX idx_product_options_product_id ON product_options (product_id);

CREATE TABLE categories (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deleted  BOOLEAN NOT NULL,
    name     VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_category_deleted_false ON categories (id) WHERE deleted = false;

CREATE TABLE category_product (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category_id BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_category_product_category_id_product_id ON category_product (category_id, product_id);
CREATE INDEX idx_category_product_product_id ON category_product (product_id);

CREATE TABLE cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deleted BOOLEAN NOT NULL,
    quantity INTEGER NOT NULL,
    product_id BIGINT NOT NULL,
    product_option_id BIGINT
);

CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     VARCHAR(255) NOT NULL,
    status       VARCHAR(255) NOT NULL,
    paid_at      TIMESTAMP(6),
    completed_at TIMESTAMP(6)
);

ALTER TABLE orders ADD CONSTRAINT uk_orders_order_id UNIQUE (order_id);

CREATE TABLE order_products (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT NOT NULL,
    product_id          BIGINT NOT NULL,
    product_title       VARCHAR(255) NOT NULL,
    product_option_id   BIGINT,
    product_option_name VARCHAR(255) NOT NULL,
    product_price       NUMERIC(38, 2) NOT NULL,
    quantity            INTEGER NOT NULL
);
